"""Supported provider-facing Drift API."""

from driftbuild.model import (
    ActionSpec,
    Artifact,
    ArtifactSpec,
    BenchmarkSpec,
    BuildConfig,
    CommandContext,
    CommandResult,
    CommandSpec,
    CompileInterface,
    Dependency,
    FileSet,
    GitHubSpec,
    LinkInterface,
    OptionSpec,
    PoolSpec,
    ProjectSpec,
    ReleaseSpec,
    RemoteSpec,
    TargetRef,
    TaskSpec,
    TestSpec,
)
from driftbuild.project import ProjectApi

__all__ = [
    "ActionSpec",
    "Artifact",
    "ArtifactSpec",
    "BenchmarkSpec",
    "BuildConfig",
    "CommandContext",
    "CommandResult",
    "CommandSpec",
    "CompileInterface",
    "Dependency",
    "FileSet",
    "GitHubSpec",
    "LinkInterface",
    "OptionSpec",
    "PoolSpec",
    "ProjectApi",
    "ProjectSpec",
    "ReleaseSpec",
    "RemoteSpec",
    "TargetRef",
    "TaskSpec",
    "TestSpec",
]
