"""Supported provider-facing Drift API."""

from driftbuild.model import (
    ActionSpec,
    ArchiveSource,
    Artifact,
    ArtifactSpec,
    BenchmarkSpec,
    BuildConfig,
    CommandContext,
    CommandResult,
    CommandSpec,
    CompileInterface,
    Dependency,
    FileSet,
    GitHubSpec,
    GitSource,
    LinkInterface,
    MsbuildProject,
    OptionSpec,
    PackageBuild,
    PackageRef,
    PackageSource,
    PackageSpec,
    PackageTargetRef,
    PoolSpec,
    ProjectSpec,
    ReleaseSpec,
    RemoteSpec,
    TargetRef,
    TaskSpec,
    TestSpec,
)
from driftbuild.project import ProjectApi

__all__ = [
    "ActionSpec",
    "ArchiveSource",
    "Artifact",
    "ArtifactSpec",
    "BenchmarkSpec",
    "BuildConfig",
    "CommandContext",
    "CommandResult",
    "CommandSpec",
    "CompileInterface",
    "Dependency",
    "FileSet",
    "GitHubSpec",
    "GitSource",
    "LinkInterface",
    "MsbuildProject",
    "OptionSpec",
    "PackageBuild",
    "PackageRef",
    "PackageSource",
    "PackageSpec",
    "PackageTargetRef",
    "PoolSpec",
    "ProjectApi",
    "ProjectSpec",
    "ReleaseSpec",
    "RemoteSpec",
    "TargetRef",
    "TaskSpec",
    "TestSpec",
]
